name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      BACKEND_TAG: oskarissimus/pythocron-backend
      FRONTEND_TAG: oskarissimus/pythocron-frontend
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: oskarissimus
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag ${{ env.BACKEND_TAG }}:latest
           docker push ${{ env.BACKEND_TAG }}:latest
