name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_TAG: oskarissimus/pythocron-backend
      FRONTEND_TAG: oskarissimus/pythocron-frontend
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: oskarissimus
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: |
        export TS=$(date +%s)
        docker build frontend --tag ${{ env.FRONTEND_TAG }}:$TS
        docker build backend --tag ${{ env.BACKEND_TAG }}:$TS
        docker tag ${{ env.FRONTEND_TAG }}:$TS ${{ env.FRONTEND_TAG }}:latest
        docker tag ${{ env.BACKEND_TAG }}:$TS ${{ env.BACKEND_TAG }}:latest
        docker push ${{ env.FRONTEND_TAG }}:$TS
        docker push ${{ env.BACKEND_TAG }}:$TS
        docker push ${{ env.FRONTEND_TAG }}:latest
        docker push ${{ env.BACKEND_TAG }}:latest
